#!/usr/bin/env bash
#
# Publishes the fastPiHole dashboard at http://pi.hole/fast by having
# Pi-hole's own webserver (pihole-FTL) serve a static redirect page
# there. Pi-hole v6 dropped lighttpd — FTL owns :80/:443 directly via
# its embedded civetweb server, which cannot reverse-proxy to an
# external backend, so this is a redirect, not a transparent proxy:
# the browser lands on http://pi.hole:<DASHBOARD_PORT>/ afterwards.
# http://<RPI_IP>:<DASHBOARD_PORT>/ keeps working exactly as before —
# nothing in this project's own code changes.
#
#   sudo ./scripts/setup-fast-path.sh              # install (or reconfigure)
#   sudo ./scripts/setup-fast-path.sh --remove     # uninstall
#   sudo ./scripts/setup-fast-path.sh --dry-run    # show, don't touch
#
# Re-running this (no flags) after changing DASHBOARD_PORT — or with
# a different --target — detects the mismatch against the already
# installed page and offers to update it instead of reporting a false
# OK. No separate "reconfigure" command needed.
#
# If webroot/fast/ already has something that ISN'T ours (no marker),
# the script refuses to touch it by default. Pass --overwrite once
# you've checked it and are sure you want it gone; add --backup to
# keep a timestamped copy first instead of just deleting it. --backup
# also applies to --remove, for the same reason.
#
# Flags: --remove --dry-run --yes --force --overwrite --backup --target <url>

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
LOG_DIR="$PROJECT_DIR/logs"
LOG_FILE="$LOG_DIR/setup-fast-path.log"
MARKER="fastPiHole-managed-file-do-not-edit"

REMOVE=0
DRY_RUN=0
ASSUME_YES=0
FORCE=0
OVERWRITE=0
BACKUP=0
TARGET_URL=""

for arg in "$@"; do
  case "$arg" in
    --remove) REMOVE=1 ;;
    --dry-run) DRY_RUN=1 ;;
    --yes) ASSUME_YES=1 ;;
    --force) FORCE=1 ;;
    --overwrite) OVERWRITE=1 ;;
    --backup) BACKUP=1 ;;
    --target=*) TARGET_URL="${arg#--target=}" ;;
    --target) : ;; # value grabbed on next iteration below
    *)
      if [ "${PREV:-}" = "--target" ]; then
        TARGET_URL="$arg"
      else
        echo "Unknown argument: $arg" >&2
        exit 1
      fi
      ;;
  esac
  PREV="$arg"
done

mkdir -p "$LOG_DIR"

log() {
  local msg="[$(date '+%Y-%m-%d %H:%M:%S')] $1"
  echo "$msg"
  echo "$msg" >>"$LOG_FILE"
}

confirm() {
  if [ "$ASSUME_YES" -eq 1 ]; then
    return 0
  fi
  read -r -p "$1 [y/N] " reply
  case "$reply" in
    [yY]|[yY][eE][sS]) return 0 ;;
    *) return 1 ;;
  esac
}

fix_log_ownership() {
  if [ -n "${SUDO_USER:-}" ]; then
    local owner
    owner="$(stat -c '%u:%g' "$PROJECT_DIR" 2>/dev/null || true)"
    if [ -n "$owner" ]; then
      chown -R "$owner" "$LOG_DIR" 2>/dev/null || true
    fi
  fi
}
trap fix_log_ownership EXIT

restart_ftl() {
  local unit=""
  for candidate in pihole-FTL pihole-FTL.service; do
    if systemctl list-unit-files --no-legend "$candidate" 2>/dev/null | grep -q .; then
      unit="$candidate"
      break
    fi
  done
  if [ -z "$unit" ]; then
    log "ERROR: systemd unit for pihole-FTL not found. Restart it manually:"
    log "  sudo service pihole-FTL restart"
    return 1
  fi
  systemctl restart "$unit"
}

verify_core() {
  local ok=1
  if command -v dig >/dev/null 2>&1; then
    if [ -z "$(dig +short +time=2 +tries=1 pi.hole @127.0.0.1 2>/dev/null)" ]; then
      log "CHECK FAILED: DNS (pi.hole) not resolving locally"
      ok=0
    fi
  fi
  local admin_code
  admin_code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 http://localhost/admin/ || echo 000)"
  case "$admin_code" in
    200|301|302|308) ;;
    *) log "CHECK FAILED: /admin/ returned $admin_code"; ok=0 ;;
  esac
  [ "$ok" -eq 1 ]
}

# Extracts the redirect target currently baked into an existing
# fastPiHole-managed page, so re-runs can detect a stale target
# (e.g. after changing DASHBOARD_PORT) instead of reporting false OK.
current_redirect_target() {
  grep -oE 'content="0; url=[^"]+"' "$1" 2>/dev/null | head -1 | sed -E 's/^content="0; url=//; s/"$//'
}

backup_target_dir() {
  local bak="${TARGET_DIR}.fastpihole-bak.$(date +%Y%m%d-%H%M%S)"
  cp -a "$TARGET_DIR" "$bak"
  log "Backed up $TARGET_DIR to $bak"
}

write_redirect_page() {
  cat >"$TARGET_FILE" <<HTML
<!doctype html>
<!-- ${MARKER} — generated by scripts/setup-fast-path.sh -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="refresh" content="0; url=${TARGET_URL}">
<title>fastPiHole</title>
</head>
<body style="background:#0a0a0a;color:#fafafa;font-family:system-ui,sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;margin:0">
<p>Redirecting to <a style="color:#fafafa" href="${TARGET_URL}">fastPiHole</a>...</p>
</body>
</html>
HTML
  chmod 644 "$TARGET_FILE"
}

# ---------------------------------------------------------------------------
# Root check
# ---------------------------------------------------------------------------
if [ "$(id -u)" -ne 0 ]; then
  echo "This script needs root (it edits Pi-hole config and restarts pihole-FTL)." >&2
  echo "Run with: sudo $0 $*" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Preflight
# ---------------------------------------------------------------------------
if ! command -v pihole-FTL >/dev/null 2>&1; then
  log "ERROR: pihole-FTL not found. This doesn't look like a Pi-hole host."
  exit 1
fi

FTL_VERSION="$(pihole-FTL version 2>/dev/null | head -1 || true)"
FTL_MAJOR="$(echo "$FTL_VERSION" | grep -oE 'v?[0-9]+' | head -1 | tr -d 'v' || true)"
if [ -z "$FTL_MAJOR" ] || [ "$FTL_MAJOR" -lt 6 ]; then
  log "ERROR: this script targets Pi-hole v6+ (pihole-FTL's embedded webserver)."
  log "Detected: '${FTL_VERSION:-unknown}'. Pi-hole v5 used lighttpd instead —"
  log "see the lighttpd appendix in README.md for that case (not automated here)."
  exit 1
fi

PORT_OWNER=""
if command -v ss >/dev/null 2>&1; then
  PORT_OWNER="$(ss -ltnp 2>/dev/null | awk '/:80[[:space:]]/ {print}' | grep -oE '"[a-zA-Z0-9_-]+"' | tr -d '"' | head -1 || true)"
elif command -v lsof >/dev/null 2>&1; then
  PORT_OWNER="$(lsof -ti tcp:80 -sTCP:LISTEN 2>/dev/null | head -1 | xargs -r ps -o comm= -p 2>/dev/null || true)"
fi

if [ -n "$PORT_OWNER" ] && [ "$PORT_OWNER" != "pihole-FTL" ]; then
  log "ERROR: port 80 is owned by '$PORT_OWNER', not pihole-FTL."
  log "This script only handles the pihole-FTL-embedded-webserver case."
  if [ "$PORT_OWNER" = "lighttpd" ]; then
    log "See the lighttpd appendix in README.md instead."
  fi
  exit 1
fi

if command -v systemctl >/dev/null 2>&1; then
  if systemctl list-unit-files --no-legend 'lighttpd*' 2>/dev/null | grep -q .; then
    log "WARNING: lighttpd is installed (likely a leftover from Pi-hole v5)."
    log "It's not running now, but if it ever starts it will fight pihole-FTL"
    log "for port 80. Consider 'apt purge lighttpd' if you don't need it."
  fi
fi

WEBROOT="$(pihole-FTL --config webserver.paths.webroot 2>/dev/null | tail -1 | tr -d '"')"
if [ -z "$WEBROOT" ] || [ ! -d "$WEBROOT" ]; then
  log "ERROR: could not resolve webserver.paths.webroot (got: '${WEBROOT:-empty}')."
  exit 1
fi

SERVE_ALL="$(pihole-FTL --config webserver.serve_all 2>/dev/null | tail -1 | tr -d '"' | tr '[:upper:]' '[:lower:]')"

DASHBOARD_PORT="$(grep -E '^DASHBOARD_PORT=' "$PROJECT_DIR/.env" 2>/dev/null | cut -d= -f2)"
DASHBOARD_PORT="${DASHBOARD_PORT:-20053}"
if ! echo "$DASHBOARD_PORT" | grep -qE '^[0-9]+$' || [ "$DASHBOARD_PORT" -lt 1 ] || [ "$DASHBOARD_PORT" -gt 65535 ]; then
  log "ERROR: DASHBOARD_PORT ('$DASHBOARD_PORT') doesn't look like a valid port."
  exit 1
fi

if [ -z "$TARGET_URL" ]; then
  TARGET_URL="http://pi.hole:${DASHBOARD_PORT}/"
fi

if ! curl -fs -o /dev/null --max-time 5 "http://localhost:${DASHBOARD_PORT}/api/auth/check"; then
  if [ "$FORCE" -eq 0 ]; then
    log "ERROR: dashboard not responding on port ${DASHBOARD_PORT}. Start it first,"
    log "or re-run with --force to proceed anyway."
    exit 1
  fi
  log "WARNING: dashboard not responding, continuing anyway (--force)."
fi

TARGET_DIR="$WEBROOT/fast"
TARGET_FILE="$TARGET_DIR/index.html"
STATE_FILE="$TARGET_DIR/.state"
TOML_FILE="/etc/pihole/pihole.toml"

# ---------------------------------------------------------------------------
# --remove
# ---------------------------------------------------------------------------
if [ "$REMOVE" -eq 1 ]; then
  if [ ! -f "$TARGET_FILE" ] || ! grep -q "$MARKER" "$TARGET_FILE" 2>/dev/null; then
    log "Nothing to remove (no fastPiHole-managed $TARGET_FILE found)."
    exit 0
  fi

  RESTORE_SERVE_ALL=0
  if [ -f "$STATE_FILE" ] && grep -q '^SERVE_ALL_WAS=false$' "$STATE_FILE" 2>/dev/null; then
    RESTORE_SERVE_ALL=1
  fi

  if [ "$DRY_RUN" -eq 1 ]; then
    [ "$BACKUP" -eq 1 ] && log "[dry-run] Would back up $TARGET_DIR first"
    log "[dry-run] Would remove $TARGET_DIR"
    [ "$RESTORE_SERVE_ALL" -eq 1 ] && log "[dry-run] Would set webserver.serve_all back to false"
    log "[dry-run] Would restart pihole-FTL if serve_all changed"
    exit 0
  fi

  confirm "Remove $TARGET_DIR and possibly restart pihole-FTL. Continue?" || { log "Aborted."; exit 1; }

  if [ -f "$TOML_FILE" ]; then
    cp -a "$TOML_FILE" "${TOML_FILE}.fastpihole-bak.$(date +%Y%m%d-%H%M%S)"
  fi

  [ "$BACKUP" -eq 1 ] && backup_target_dir

  rm -rf "$TARGET_DIR"
  log "Removed $TARGET_DIR"

  if [ "$RESTORE_SERVE_ALL" -eq 1 ]; then
    confirm "Restart pihole-FTL to restore webserver.serve_all=false? This briefly interrupts DNS for the network." \
      && { pihole-FTL --config webserver.serve_all false; restart_ftl; } \
      || log "Skipped restart — serve_all left as-is, run again later if you want it reverted."
  fi

  verify_core || log "WARNING: post-removal core checks failed, review manually."
  exit 0
fi

# ---------------------------------------------------------------------------
# Idempotency check (install path)
# ---------------------------------------------------------------------------
if [ -f "$TARGET_FILE" ]; then
  if grep -q "$MARKER" "$TARGET_FILE"; then
    CURRENT_TARGET="$(current_redirect_target "$TARGET_FILE")"

    if [ "$CURRENT_TARGET" = "$TARGET_URL" ]; then
      log "Already installed at $TARGET_FILE, pointing at $TARGET_URL. Re-verifying..."
      if curl -s --max-time 5 "http://localhost/fast/" 2>/dev/null | grep -q "$MARKER" \
        && curl -fs -o /dev/null --max-time 5 "http://localhost:${DASHBOARD_PORT}/api/auth/check"; then
        log "OK: http://pi.hole/fast is live and points to a healthy dashboard."
        exit 0
      else
        log "WARNING: file present but verification failed. Re-run without changes"
        log "made yet, or use --remove then re-install."
        exit 1
      fi
    fi

    log "Installed, but pointing at a different target:"
    log "  currently:  ${CURRENT_TARGET:-<unreadable>}"
    log "  should be:  $TARGET_URL"
    log "(this happens after changing DASHBOARD_PORT, or after --target)."

    if [ "$DRY_RUN" -eq 1 ]; then
      log "[dry-run] Would update $TARGET_FILE to point at $TARGET_URL"
      exit 0
    fi

    confirm "Update the redirect to point at $TARGET_URL?" || { log "Left as-is."; exit 1; }

    write_redirect_page
    log "Updated $TARGET_FILE -> $TARGET_URL"

    if curl -s --max-time 5 "http://localhost/fast/" 2>/dev/null | grep -qF "$TARGET_URL" \
      && curl -fs -o /dev/null --max-time 5 "http://localhost:${DASHBOARD_PORT}/api/auth/check"; then
      log "SUCCESS: http://pi.hole/fast now redirects to $TARGET_URL"
      exit 0
    else
      log "WARNING: page updated but verification failed — check $LOG_FILE and the"
      log "dashboard on port ${DASHBOARD_PORT}."
      exit 1
    fi
  else
    log "ERROR: $TARGET_FILE already exists and is NOT managed by fastPiHole."

    if [ "$OVERWRITE" -ne 1 ]; then
      log "Refusing to overwrite. Move it aside manually and re-run, or pass"
      log "--overwrite (add --backup to keep a copy of it first)."
      exit 1
    fi

    if [ "$DRY_RUN" -eq 1 ]; then
      [ "$BACKUP" -eq 1 ] && log "[dry-run] --overwrite --backup set: would back up $TARGET_DIR, then remove and reinstall"
      [ "$BACKUP" -eq 0 ] && log "[dry-run] --overwrite set: would remove $TARGET_DIR (no backup) and reinstall"
      exit 0
    fi

    log "WARNING: --overwrite set. $TARGET_DIR was not created by fastPiHole:"
    ls -la "$TARGET_DIR"
    confirm "Really overwrite $TARGET_DIR?" || { log "Aborted."; exit 1; }

    [ "$BACKUP" -eq 1 ] && backup_target_dir

    rm -rf "$TARGET_DIR"
    log "Removed pre-existing $TARGET_DIR, proceeding with a fresh install"
    # falls through to the install section below
  fi
fi

# ---------------------------------------------------------------------------
# Dry run summary
# ---------------------------------------------------------------------------
if [ "$DRY_RUN" -eq 1 ]; then
  log "[dry-run] Would create $TARGET_FILE redirecting to $TARGET_URL"
  if [ "$SERVE_ALL" != "true" ]; then
    log "[dry-run] Would set webserver.serve_all=true (currently: $SERVE_ALL)"
    log "[dry-run] Would restart pihole-FTL (briefly interrupts DNS)"
  else
    log "[dry-run] webserver.serve_all is already true, no restart needed"
  fi
  exit 0
fi

# ---------------------------------------------------------------------------
# Install
# ---------------------------------------------------------------------------
log "Webroot: $WEBROOT"
log "serve_all currently: $SERVE_ALL"

if [ -f "$TOML_FILE" ]; then
  cp -a "$TOML_FILE" "${TOML_FILE}.fastpihole-bak.$(date +%Y%m%d-%H%M%S)"
  log "Backed up $TOML_FILE"
fi

install -d -m 755 "$TARGET_DIR"

write_redirect_page
log "Created $TARGET_FILE -> $TARGET_URL"

NEED_RESTART=0
if [ "$SERVE_ALL" != "true" ]; then
  echo "Contents of $WEBROOT (will become fully servable on :80 with serve_all=true):"
  ls -la "$WEBROOT"
  confirm "Enable webserver.serve_all? Required for /fast to be reachable." \
    || { log "Aborted before changing serve_all. $TARGET_FILE left in place but unreachable."; exit 1; }
  pihole-FTL --config webserver.serve_all true
  echo "SERVE_ALL_WAS=false" >"$STATE_FILE"
  chmod 644 "$STATE_FILE"
  NEED_RESTART=1
  log "Set webserver.serve_all=true"
else
  echo "SERVE_ALL_WAS=true" >"$STATE_FILE"
  chmod 644 "$STATE_FILE"
fi

if [ "$NEED_RESTART" -eq 1 ]; then
  confirm "Restart pihole-FTL now to apply? This briefly interrupts DNS for the whole network." \
    || { log "Aborted before restart. Config changed but not applied — restart pihole-FTL manually when ready."; exit 1; }
  if ! restart_ftl; then
    log "ERROR: restart failed. Restore backup manually if needed: ${TOML_FILE}.fastpihole-bak.*"
    exit 1
  fi
  sleep 2
fi

# ---------------------------------------------------------------------------
# Verify
# ---------------------------------------------------------------------------
FAILED_CORE=0
verify_core || FAILED_CORE=1

if [ "$FAILED_CORE" -eq 1 ]; then
  log "ERROR: core checks failed after install. Rolling back..."
  LATEST_BAK="$(ls -t "${TOML_FILE}".fastpihole-bak.* 2>/dev/null | head -1)"
  if [ -n "$LATEST_BAK" ]; then
    cp -a "$LATEST_BAK" "$TOML_FILE"
  fi
  rm -rf "$TARGET_DIR"
  restart_ftl || true
  log "Rolled back. Pi-hole should be back to its previous state — please verify manually."
  exit 1
fi

FAST_OK=1
curl -s --max-time 5 "http://localhost/fast/" 2>/dev/null | grep -q "$MARKER" || FAST_OK=0
DASH_OK=1
curl -fs -o /dev/null --max-time 5 "http://localhost:${DASHBOARD_PORT}/api/auth/check" || DASH_OK=0

if [ "$FAST_OK" -eq 1 ] && [ "$DASH_OK" -eq 1 ]; then
  log "SUCCESS: http://pi.hole/fast now redirects to $TARGET_URL"
else
  log "WARNING: Pi-hole's admin panel and DNS look fine, but /fast isn't fully"
  log "working yet (fast page reachable: $FAST_OK, dashboard healthy: $DASH_OK)."
  log "Nothing destructive was rolled back since the core system is healthy —"
  log "check $LOG_FILE and try again."
fi
